name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./dkp.sh

    - name: Install dependencies
      run: make

    - name: Run check
      run: make wah

    - name: Run distcheck
      run: make dist
