name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest


    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run:  make nxExt -j66 && (make overlay -j66 && echo "Overlay Made"; make module -j66 && echo "Module made"; make sys-tune -j66 && echo "MAIN MADE";) && echo next;

    - name: Run check
      run: make wah

    - name: Run distcheck
      run: make dist
      
    - uses: actions/upload-artifact@master
      with:
        name: sys-tune
        path: dist
