name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v3

    - name: make clean
      run: |
        make clean 

    - name: nxExt
      run: | 
        make nxExt 
      
    - name: module
      run: |
        make module
        
    - name: overlay
      run: |
        make overlay

    - name: systune
      run: | 
        make all 
    
    - name: final
      run: | 
        make dist
      
    - uses: actions/upload-artifact@master
      with:
        name: sys-tune
        path: dist
