name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v3

    - name: make clean
      run: |
        make clean

    - name: nxExt
      run: | 
        make nxExt -j66666     
      
    - name: module
      run: |
        make module -j6666

    - name: overlay
      run: |
        make overlay -j666

    - name: losers
      run: |
        make wah -j66

    - name: systune
      run: | 
        make all -j6
    
    - name: final
      run: | 
        make dist
      
    - uses: actions/upload-artifact@master
      with:
        name: sys-tune
        path: dist
