name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v3

    - name: make clean
      run: make clean

    - name: nxExt
      run: make nxExt -j666      
      
    - name: module
      run: make module -j666

    - name: overlay
      run: make overlay -j666

    - name: systune
      run: make all

    - name: final
      run: make wah dist -j66
      
    - uses: actions/upload-artifact@master
      with:
        name: sys-tune
        path: dist
